apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31771
